Version update 0.4.0
NVIDIA/modulus pull request #227
Opened 2023-11-08 18:41 UTC by ktangsali

# Modulus Pull Request

## Description
Updates the version

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

## Dependencies

2023-11-08 20:53 UTC, NickGeneva requested changes

2023-11-08 20:53 UTC, NickGeneva commented on CHANGELOG.md
> +## [0.4.0] - 2023-11-xx
put the 13th here

2023-11-08 20:53 UTC, NickGeneva commented
Please also update the docker versions in the readme to 23.11 before we forget.

2023-11-08 21:02 UTC, ktangsali commented
> Please also update the docker versions in the readme to 23.11 before we forget.

Thanks! Done

2023-11-08 23:45 UTC, NickGeneva approved these changes

2023-11-09 22:02 UTC, akshaysubr approved these changes

2023-11-09 22:30 UTC, ktangsali commented
/blossom-ci

2023-11-09 22:56 UTC, merged