add VFGN utils and model code
NVIDIA/modulus pull request #68
Opened 2023-07-14 22:31 UTC by dearleiii

HP Virtual Foundry Graphnet - add VFGN utils code and model code

2023-07-17 14:20 UTC, mnabian requested changes

2023-07-17 14:20 UTC, mnabian commented on modulus/utils/vfgn/reading_utils.py
> +  trajectory_length = 14+24
Would be nice to get rid of the hard-coded sequence length here

2023-07-17 14:20 UTC, mnabian commented on modulus/models/vfgn/graph_network.py
> +        # self.node_mlp = MLPNet(mlp_hidden_size, mlp_num_hidden_layers, output_size)
Please remove the commented out code.

2023-07-17 14:20 UTC, mnabian commented on modulus/models/vfgn/graph_network.py
> +class LearnedSimulator(torch.nn.Module):
I suggest we move the data loading/processing modules to the `datapipes` folder to better organize the code.

2023-07-17 14:20 UTC, mnabian commented on modulus/models/vfgn/graph_network.py
In general, there's a lot of overlap between this code and the MeshGraphNet code here: https://github.com/NVIDIA/modulus/blob/main/modulus/models/meshgraphnet/meshgraphnet.py. It is highly recommended to use the existing modules as much as possible and minimize code duplication.

2023-08-14 17:06 UTC, dearleiii commented on modulus/models/vfgn/graph_network.py
> +    def __init__(self, mlp_hidden_size, mlp_num_hidden_layers, output_size, layer_norm=True):
discussed and agreed to keep the current implementation

2024-02-07 08:43 UTC, closed without merging