add calls to init, fix time format warning
NVIDIA/modulus pull request #681
Opened 2024-09-20 17:21 UTC by yairchn

## Description
in the current code `from modulus.datapipes.healpix import CoupledTimeSeriesDataModule` does not work. This PR closes issue #680 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is up to date with these changes.
- [x] An [issue](https://github.com/NVIDIA/modulus/issues) is linked to this pull request.

2024-09-23 19:03 UTC, akshaysubr approved these changes

2024-09-23 19:26 UTC, daviddpruitt commented
/blossom-ci

2024-09-23 19:28 UTC, daviddpruitt approved these changes

2024-09-23 20:54 UTC, daviddpruitt commented
/blossom-ci

2024-09-23 23:41 UTC, dallasfoster requested changes

2024-09-23 23:41 UTC, dallasfoster commented on modulus/datapipes/__init__.py
> +from . import healpix
Hi @yairchn, to follow convention for the rest of the datapipes, I am inclined to suggest removing this import statement. The reason is that each of the submodule datapipes may require various non-required packages and putting them in this level will require all `modulus.datapipe` users to have those dependencies. In this case, the use of `omegaconf` is an optional dependency in modulus but required for `healpix` datapipes.

2024-09-25 20:27 UTC, dallasfoster approved these changes

2024-09-25 20:27 UTC, dallasfoster commented
/blossom-ci

2024-09-26 17:19 UTC, dallasfoster commented
/blossom-ci

2024-09-27 23:44 UTC, dallasfoster commented
/blossom-ci

2024-09-30 16:05 UTC, merged